//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linkedin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileEducation
    {
        public int ProfileID { get; set; }
        public string Education { get; set; }
        public int ID { get; set; }
    
        public virtual ProfileDetails ProfileDetails { get; set; }
    }
}
