//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Linkedin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProfileDetails()
        {
            this.ProfileEducation = new HashSet<ProfileEducation>();
            this.ProfileExperience = new HashSet<ProfileExperience>();
            this.ProfileSkills = new HashSet<ProfileSkills>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string currentTitle { get; set; }
        public string CurrentPosition { get; set; }
        public string Summary { get; set; }
        public Nullable<int> Score { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileEducation> ProfileEducation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileExperience> ProfileExperience { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfileSkills> ProfileSkills { get; set; }
    }
}
